Added the ability to add filters
JJerome-NM/WebSocketHelper pull request #2
Opened 2023-03-27 20:48 UTC by JJerome-NM

2023-04-04 10:06 UTC, justme1135 requested changes

2023-04-04 10:23 UTC, getmane requested changes
1. We do not use the test package as a place for regular production code
2. Remove all the comments you currently have
3. Rewrite your code so that it makes sense without comments

General advice, please define some description of what you are aiming to achieve in this PR. Just from reading your code, it does not make sense at all to me.

2023-04-04 13:06 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/SocketApplication.java
>  import java.util.*;
Changed imports to normal

2023-04-04 13:06 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/SocketApplication.java
>  import org.jetbrains.annotations.NotNull;
Changed Jetbrains @NotNull to lombok.NonNull

2023-04-04 13:06 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/context/SocketControllersContext.java
>  import java.util.*;
Changed imports to normal

2023-04-04 13:06 UTC, JJerome-NM commented on jjsocket-main/src/test/java/com/jjerome/test/MainTests/ConnectFilter.java
> +import org.jetbrains.annotations.NotNull;
Changed Jetbrains @NotNull to lombok.NonNull

2023-04-05 07:21 UTC, justme1135 approved these changes

2023-04-05 08:49 UTC, merged