New responses
JJerome-NM/WebSocketHelper pull request #3
Opened 2023-03-31 15:12 UTC by JJerome-NM

1. Add a message sending controller
2. Change mappings from "request - response" to just "request".
3. Add filter order.
4. Change the response header.

2023-04-04 10:34 UTC, justme1135 requested changes

2023-04-04 10:34 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/context/SocketControllersContext.java
> +import com.jjerome.annotations.*;
Remove single imports

2023-04-04 10:34 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/context/SocketControllersContext.java
>  import java.util.*;
Same here

2023-04-04 10:34 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/filters/FiltersComparator.java
> +        return result != 0 ? result : f1 == f2 ? 0 : -1;
Rewrite it so it becomes more readable and not so complex

2023-04-04 10:34 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/models/SocketApplication.java
> +    }
Refactor without using initialization blocks

2023-04-04 15:47 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/context/SocketControllersContext.java
> +import com.jjerome.annotations.*;
I modified it for normal imports

2023-04-04 15:47 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/context/SocketControllersContext.java
>  import java.util.*;
This is also fixed here

2023-04-04 15:48 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/mappers/ResponseMapper.java
> +        return response;
Made fewer retours

2023-04-04 15:49 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/filters/FiltersComparator.java
> +        return result != 0 ? result : f1 == f2 ? 0 : -1;
I made it a little simpler

2023-04-04 15:49 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/SocketApplication.java
> +    }
Removed this initialization block

2023-04-04 18:40 UTC, justme1135 requested changes

2023-04-04 18:40 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/filters/FiltersComparator.java
> +        return result != 0 ? result : f1 == f2 ? 0 : -1;
If you do the `f1 == f2` check and return directly after line 12 it becomes easier to read

2023-04-04 18:40 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/annotations/FilteringOrder.java
> +import java.lang.annotation.*;
Remove wildcard imports

2023-04-04 18:40 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/annotations/SocketComponentsScan.java
> +import java.lang.annotation.*;
Same here

2023-04-04 18:40 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/annotations/SocketMappingFilters.java
> +import java.lang.annotation.*;
Same here

2023-04-04 19:39 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/annotations/FilteringOrder.java
> +import java.lang.annotation.*;
Removed wildcard imports

2023-04-04 19:39 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/annotations/SocketComponentsScan.java
> +import java.lang.annotation.*;
Removed wildcard imports

2023-04-04 19:39 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/annotations/SocketMappingFilters.java
> +import java.lang.annotation.*;
Removed wildcard imports

2023-04-04 19:41 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/filters/FiltersComparator.java
> +        return result != 0 ? result : f1 == f2 ? 0 : -1;
Added a check after line 12

2023-04-05 07:10 UTC, justme1135 requested changes
Few small fixes and you are good to go

2023-04-05 07:10 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/models/RequestAccepter.java
> +    public RequestAccepter(Map<String, BiConsumer<WebSocketSession ,TextMessage>> methodMappings,
Replace with `@RequiredArgsConstructor` on class

2023-04-05 07:10 UTC, justme1135 commented on jjsocket-main/src/main/java/com/jjerome/models/ResponseErrors.java
> +    public Response<String> get(){
Replace explicit getter with `@Getter` annotation

2023-04-05 07:10 UTC, justme1135 commented on .gitignore
> +MainTests
This entry bothers me a little. So you have some tests set up and you explicitly ignore them? Would not it be better just to remove them?

2023-04-05 09:30 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/RequestAccepter.java
> +import org.jetbrains.annotations.NotNull;
I fixed it, unfortunately I didn't find it before

2023-04-05 09:30 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/RequestAccepter.java
> +    public RequestAccepter(Map<String, BiConsumer<WebSocketSession ,TextMessage>> methodMappings,
Added this annotation, very good recommendation

2023-04-05 09:31 UTC, JJerome-NM commented on jjsocket-main/src/main/java/com/jjerome/models/ResponseErrors.java
> +    public Response<String> get(){
Removed that method and added the @Getter annotation

2023-04-05 09:33 UTC, JJerome-NM commented on .gitignore
> +MainTests
They were bad tests, so I didn't want them to hit the gate. Although I think I removed them in the previous commit

2023-04-05 09:54 UTC, justme1135 approved these changes

2023-04-05 09:56 UTC, merged