Reworking to beans
JJerome-NM/WebSocketHelper pull request #4
Opened 2023-04-05 20:01 UTC by JJerome-NM

The library has been converted from a multi-module to a regular project, the launcher has been redesigned using Beans.

2023-04-09 15:30 UTC, justme1135 requested changes

2023-04-09 15:30 UTC, justme1135 commented on src/main/java/com/jjerome/annotations/SocketController.java
>  import java.lang.annotation.*;
Rewrite to single imports

2023-04-09 15:30 UTC, justme1135 commented on src/main/java/com/jjerome/models/BeanUtil.java
> +            LOGGER.warn("OMGGGGGGGGGGGGGGG You have more than two SpringBootApplications, this can cause errors");
Really funny but please rewrite to more meaningful message.

2023-04-09 15:30 UTC, justme1135 commented on src/main/java/com/jjerome/context/SocketControllersContext.java
> +        } else if (method.getParameterCount() != parameterClasses.length) {
not need for `else` if you are already using `return` in previous condition

2023-04-09 17:12 UTC, JJerome-NM commented on src/main/java/com/jjerome/annotations/SocketController.java
>  import java.lang.annotation.*;
Fixed

2023-04-09 17:12 UTC, JJerome-NM commented on src/main/java/com/jjerome/models/BeanUtil.java
> +            LOGGER.warn("OMGGGGGGGGGGGGGGG You have more than two SpringBootApplications, this can cause errors");
I redesigned it to make it more informative

2023-04-09 17:14 UTC, JJerome-NM commented on src/main/java/com/jjerome/context/SocketControllersContext.java
> +        } else if (method.getParameterCount() != parameterClasses.length) {
Yes you are right, I fixed it

2023-04-13 19:45 UTC, justme1135 approved these changes

2023-04-18 15:35 UTC, merged